server:
    port: 8761 #默认端口
spring:
    application:
        name: server-eureka #服务名，最好写，方便识别
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/  #Eureka注册中心的路径
        register-with-eureka: false #不把自己注册进eureka
        fetch-registry: false #不从eureka中获取注册信息
